/**
 * USER Mutations USER Mutations
 */
export const MUTATIONS_USER__SET_TOKEN = 'MUTATIONS_USER__SET_TOKEN';
export const MUTATIONS_USER__REMOVE_TOKEN = 'MUTATIONS_USER__REMOVE_TOKEN';
export const MUTATIONS_USER__SET_REFRESHTOKEN =
  'MUTATIONS_USER__SET_REFRESHTOKEN';
export const MUTATIONS_USER__REMOVE_REFRESHTOKEN =
  'MUTATIONS_USER__REMOVE_REFRESHTOKEN';
export const MUTATIONS_USER__SET_USERINFO = 'MUTATIONS_USER__SET_USERINFO';
export const MUTATIONS_USER__CLEAR_USERINFO = 'MUTATIONS_USER__CLEAR_USERINFO';
export const MUTATIONS_USER__SET_ROUTER = 'MUTATIONS_USER__SET_ROUTER';
export const MUTATIONS_USER__CLEAR_ROUTER = 'MUTATIONS_USER__CLEAR_ROUTER';
export const MUTATIONS_USER__SET_PERMISSION = 'MUTATIONS_USER__SET_PERMISSION';
export const MUTATIONS_USER__CLEAR_PERMISSION =
  'MUTATIONS_USER__CLEAR_PERMISSION';
export const MUTATIONS_USER__SET_ROLES = 'MUTATIONS_USER__SET_ROLES';
export const MUTATIONS_USER__CLEAR_ROLES = 'MUTATIONS_USER__CLEAR_ROLES';
export const MUTATIONS_USER__SET_MENU = 'MUTATIONS_USER__SET_MENU';
export const MUTATIONS_USER__CLEAR_MENU = 'MUTATIONS_USER__CLEAR_MENU';
export const MUTATIONS_USER__CLEAR = 'MUTATIONS_USER__CLEAR';
/**
 * USER Mutations USER Mutations
 */

/**
 * MENU Mutations MENU Mutations
 */
export const MUTATIONS_TAG__ACTIVE = 'MUTATIONS_TAG__ACTIVE';
export const MUTATIONS_TAG__ADD = 'MUTATIONS_TAG__ADD';
export const MUTATIONS_TAG__CLOSE = 'MUTATIONS_TAG__CLOSE';
export const MUTATIONS_TAG__CLOSE_OTHER = 'MUTATIONS_TAG__CLOSE_OTHER';
export const MUTATIONS_TAG__CLEAR = 'MUTATIONS_TAG__CLEAR';
export const MUTATIONS_TAG__CLEARALL = 'MUTATIONS_TAG__CLEARALL';
